name: n8n Docker Workflow

on:
  workflow_dispatch:

jobs:
  run-n8n:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create credentials directory
        run: mkdir -p ~/.n8n

      - name: Set up n8n credentials from secret
        run: echo '${{ secrets.N8N_CREDENTIALS_JSON }}' > ~/.n8n/credentials.json

      - name: Run n8n Docker container and execute workflow
        run: |
          docker run --rm \
            -e N8N_ENCRYPTION_KEY='${{ secrets.N8N_ENCRYPTION_KEY }}' \
            -v $(pwd):/data \
            -v ~/.n8n:/home/node/.n8n \
            n8nio/n8n:latest \
            n8n execute --workflow=/data/workflow.json --log-level=debug
