name: Run n8n Workflow

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-n8n:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker and FFmpeg
        run: sudo apt-get update && sudo apt-get install -y docker.io ffmpeg

      - name: Run n8n container
        run: |
          docker run -d --name n8n \
            -e N8N_ENCRYPTION_KEY=${{ secrets.N8N_ENCRYPTION_KEY }} \
            -v ${{ github.workspace }}:/home/node/.n8n \
            n8nio/n8n:latest
          sleep 20

      - name: Execute n8n workflow
        run: docker exec n8n n8n execute --file /home/node/.n8n/workflow.json

