name: Final n8n Workflow

on:
  workflow_dispatch:

jobs:
  run-n8n:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Replace placeholders with secrets
        run: |
          sed -i 's|_PLACEHOLDER_OPENAI_API_KEY_|${{ secrets.OPENAI_API_KEY }}|g' n8n-workflow.json

      - name: Install and Run n8n
        run: |
          npm install -g n8n
          n8n execute --workflow=n8n-workflow.json --log-level=debug
